author: Xen0Xys
name: Xen0Lib
version: 1.1.8
api-version: 1.19
main: fr.xen0xys.xen0lib.plugin.Xen0Lib

commands:
  xdev:
    permission: xen0lib.xdev

permissions:
  xen0lib.*:
    description: Gives access to all Xen0Lib commands
    children:
      xen0lib.xdev: true
  xen0lib.xdev:
    default: op